# Generated by Django 4.1.7 on 2023-03-05 09:34
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("blog", "0002_initial")]

    operations = [
        migrations.RemoveField(model_name="post", name="image"),
        migrations.RemoveField(model_name="postcomment", name="image"),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(max_length=4096, verbose_name="text"),
        ),
        migrations.AlterField(
            model_name="postcomment",
            name="text",
            field=models.TextField(max_length=4096, verbose_name="text"),
        ),
    ]
