# Generated by Django 4.1.7 on 2023-03-05 12:55
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("blog", "0004_rename_date_post_date_created_and_more")]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="date created"
            ),
        ),
        migrations.AlterField(
            model_name="postcomment",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="date created"
            ),
        ),
    ]
