# Generated by Django 4.1.7 on 2023-03-05 14:56
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("blog", "0005_alter_post_date_created_and_more")]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="user", new_name="author"
        ),
        migrations.RenameField(
            model_name="postcomment", old_name="user", new_name="author"
        ),
    ]
