# Generated by Django 4.1.7 on 2023-03-05 15:04
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("blog", "0007_alter_post_author_alter_postcomment_author")]

    operations = [
        migrations.RenameField(model_name="post", old_name="text", new_name="content"),
        migrations.RenameField(
            model_name="postcomment", old_name="text", new_name="content"
        ),
    ]
