# Generated by Django 4.1.7 on 2023-03-05 15:05
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("blog", "0008_rename_text_post_content_and_more")]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(max_length=4096, verbose_name="content"),
        ),
        migrations.AlterField(
            model_name="postcomment",
            name="content",
            field=models.TextField(max_length=4096, verbose_name="content"),
        ),
    ]
