# Generated by Django 4.1.7 on 2023-03-05 20:28
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_post_content_alter_postcomment_content")
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="date updated"
            ),
        ),
        migrations.AddField(
            model_name="postcomment",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="date updated"
            ),
        ),
    ]
