# Generated by Django 4.2.1 on 2023-05-28 15:32
from __future__ import annotations

from django.db import migrations, models

import socnet.core.fields


class Migration(migrations.Migration):
    dependencies = [("blog", "0012_comment_delete_postcomment")]

    operations = [
        migrations.AddField(
            model_name="post",
            name="allow_commenting",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "You can comment on your posts regardless of this setting."
                ),
                verbose_name="allow commenting",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(
                help_text="Supports a safe subset of HTML and Markdown.",
                max_length=16384,
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date_updated",
            field=socnet.core.fields.NullAutoNowDateTimeField(
                auto_now=True, null=True, verbose_name="date updated"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(
                help_text="Supports a safe subset of HTML and Markdown.",
                max_length=16384,
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="date_updated",
            field=socnet.core.fields.NullAutoNowDateTimeField(
                auto_now=True, null=True, verbose_name="date updated"
            ),
        ),
    ]
