# Generated by Django 4.2.2 on 2023-06-09 18:40
from __future__ import annotations

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_post_allow_commenting_alter_comment_content_and_more")
    ]

    operations = [TrigramExtension()]
