version: 2
updates:
  - package-ecosystem: docker
    directory: /docker/caddy/
    schedule:
      interval: daily
      time: "04:30"
  - package-ecosystem: docker
    directory: /docker/django/
    schedule:
      interval: daily
      time: "04:30"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "04:30"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "04:30"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
      time: "04:30"
