version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "15:00"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
      time: "15:00"
