version: 2
updates:
  - package-ecosystem: cargo
    directory: /socnet_rs/
    schedule:
      interval: daily
      time: "04:30"
  - package-ecosystem: docker
    directory: /docker/caddy/
    schedule:
      interval: daily
      time: "04:30"
  - package-ecosystem: docker
    directory: /docker/django/
    schedule:
      interval: daily
      time: "04:30"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "04:30"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "04:30"
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
      time: "04:30"
    groups:
      mypy:
        patterns:
          - django-stubs
          - django-stubs-ext
          - djangorestframework-stubs
          - mypy
