version: 2
updates:
  - package-ecosystem: cargo
    directory: /socnet_rs/
    schedule:
      interval: daily
      time: "02:30"
    groups:
      cargo-semver-minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: docker
    directory: /docker/caddy/
    schedule:
      interval: daily
      time: "02:30"
  - package-ecosystem: docker
    directory: /docker/django/
    schedule:
      interval: daily
      time: "02:30"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "02:30"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "02:30"
    groups:
      npm-semver-minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
      time: "02:30"
    groups:
      pip-semver-minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
