name: socnet
services:
  django:
    build:
      dockerfile: ./docker/django/Dockerfile
      pull: true
    depends_on:
      - postgres
    env_file: ./.env
    init: true
    networks:
      - django-postgres
  postgres:
    image: docker.io/postgres:17
    env_file: ./.env
    init: true
    networks:
      - django-postgres
    pull_policy: always
networks:
  django-postgres:
