services:
  django:
    image: socnet-production-django
    build:
      target: python-production-run-stage
      args:
        - EXTRA=production
    depends_on:
      - redis
    networks:
      - caddy-django
      - django-redis
    restart: on-failure
    volumes:
      - production-django-media:/var/www/django/media
      - production-django-static:/var/www/django/static
  postgres:
    restart: on-failure
    volumes:
      - production-postgres-data:/var/lib/postgresql/data
  redis:
    image: docker.io/valkey/valkey:8
    init: true
    logging:
      driver: local
    networks:
      - django-redis
    pull_policy: always
    restart: on-failure
  caddy:
    build:
      dockerfile: ./docker/caddy/Dockerfile
      pull: true
    cap_add:
      - NET_ADMIN
    depends_on:
      - django
    env_file: ./.env
    init: true
    logging:
      driver: local
    networks:
      - caddy-django
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    restart: on-failure
    volumes:
      - production-caddy-config:/config
      - production-caddy-data:/data
      - production-django-media:/var/www/django/media
      - production-django-static:/var/www/django/static
networks:
  caddy-django:
  django-redis:
volumes:
  production-caddy-config:
  production-caddy-data:
  production-django-media:
  production-django-static:
  production-postgres-data:
