services:
  django:
    image: socnet-local-django
    build:
      target: python-local-run-stage
      args:
        - EXTRA=local
    depends_on:
      - esbuild
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
  postgres:
    volumes:
      - local-postgres-data:/var/lib/postgresql/data
  esbuild:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      target: node-watch-stage
    init: true
    logging:
      driver: local
    networks:
      - esbuild
    volumes:
      - ./socnet/static/private:/app/socnet/static/private
      - ./socnet/static/public:/app/socnet/static/public
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
networks:
  esbuild:
volumes:
  local-postgres-data:
