services:
  django:
    image: socnet-local-django
    build:
      args:
        - "EXTRA=local"
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
      target: python-local
    depends_on:
      - esbuild
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
  postgres:
    volumes:
      - local-postgres-data:/var/lib/postgresql/data
  esbuild:
    build:
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
      dockerfile: ./docker/django/Dockerfile
      pull: true
      target: node-watch
    init: true
    logging:
      driver: local
    networks:
      - esbuild
    volumes:
      - ./socnet/static/private:/app/socnet/static/private
      - ./socnet/static/public:/app/socnet/static/public
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
networks:
  esbuild:
volumes:
  local-postgres-data:
