blank_line_after_tag = ["extends", "load"]
close_void_tags = true
format_attribute_template_tags = false
ignore = ["H013"]
include = ["H017", "T003"]
indent = 2
max_line_length = 80
name_endblocks = true
no_indent_inner_html = true
profile = "django"
single_attribute_per_line = true
sort_attributes = true
