services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        - GID=${GID:-1000}
        - UID=${UID:-1000}
    depends_on:
      - postgres
    env_file: ./.env
    restart: unless-stopped

  postgres:
    image: postgres:14
    env_file: ./.env
    restart: unless-stopped
