services:
  django:
    image: socnet_local_django
    build:
      target: python-local-run-stage
      args:
        - POETRY_GROUPS=main,local
        - GID=${GID:-1000}
        - UID=${UID:-1000}
    command:
      - /usr/local/bin/uvicorn
      - --host
      - 0.0.0.0
      - --reload
      - --reload-include
      - "*.html"
      - --log-config
      - config/settings/logging.json
      - --no-server-header
      - config.asgi:application
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - socnet_local_javascript:/app/socnet/static/public/js/:ro
  postgres:
    volumes:
      - socnet_local_postgres_data:/var/lib/postgresql/data
  tsc:
    image: socnet_tsc
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      target: node
    command:
      - npx
      - tsc
      - --watch
      - --preserveWatchOutput
    restart: unless-stopped
    user: node
    volumes:
      - ./socnet/static/private/ts/:/app/socnet/static/private/ts/:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - socnet_local_javascript:/app/socnet/static/public/js/
volumes:
  socnet_local_postgres_data:
  socnet_local_javascript:
