name: socnet
services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    depends_on:
      - postgres
    env_file: ./.env
    networks:
      - django-postgres
  postgres:
    image: docker.io/postgres:17
    env_file: ./.env
    networks:
      - django-postgres
networks:
  django-postgres:
