# Compose file for development and production.
# Should be used together with `docker/docker-compose.prod.yml` in production.
version: "3.8"
services:
  db:
    image: "postgres:14-alpine"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet
    env_file: ./config/.env

  redis:
    image: "redis:7-alpine"
    restart: unless-stopped
    networks:
      - webnet

  web:
    <<: &web
      image: "socnet:dev"
      build:
        target: development_build
        context: .
        dockerfile: ./docker/django/Dockerfile
        args:
          DJANGO_ENV: development
        cache_from:
          - "socnet:dev"
          - "socnet:latest"
          - "*"

      volumes:
        - django-static:/var/www/django/static
      depends_on:
        - db
        - redis
      networks:
        - webnet
      env_file: ./config/.env
      environment:
        DJANGO_DATABASE_HOST: db
        DJANGO_REDIS_HOST: redis

    command: python -Wd manage.py runserver 0.0.0.0:8000

networks:
  webnet:

volumes:
  pgdata:
  django-static:
