services:
  django:
    image: socnet_local_django
    build:
      target: python-local-run-stage
      args:
        - BUILD_ENVIRONMENT=local
        - GID=${GID:-1000}
        - UID=${UID:-1000}
    command:
      [
        "/usr/local/bin/uvicorn",
        "config.asgi:application",
        "--host",
        "0.0.0.0",
        "--reload",
      ]
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  postgres:
    volumes:
      - socnet_local_postgres_data:/var/lib/postgresql/data

volumes:
  socnet_local_postgres_data:
