services:
  django:
    image: socnet_production_django
    build:
      target: python-production-run-stage
      args:
        - POETRY_GROUPS=main,production
    command:
      - bash
      - /app/docker/django/start.sh
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    networks:
      - redis
      - caddy
    volumes:
      - production_django_media:/var/www/django/media
      - production_django_static:/var/www/django/static
  postgres:
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    networks:
      - redis
    restart: unless-stopped
  caddy:
    image: socnet_production_caddy
    build:
      context: .
      dockerfile: ./docker/caddy/Dockerfile
    depends_on:
      - django
    env_file: ./.env
    networks:
      - caddy
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - production_caddy_config:/config
      - production_caddy_data:/data
      - production_django_media:/var/www/django/media
      - production_django_static:/var/www/django/static
networks:
  redis:
  caddy:
volumes:
  production_caddy_config:
  production_caddy_data:
  production_django_media:
  production_django_static:
  production_postgres_data:
