services:
  django:
    image: socnet_local_django
    build:
      target: python-local-stage
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        - BUILD_ENVIRONMENT=local
        - GID=${GID:-1000}
        - UID=${UID:-1000}
    command: python3 -Wd manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    env_file: ./.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .:/app

  postgres:
    image: postgres:14
    env_file: ./.env
    restart: unless-stopped
    volumes:
      - socnet_local_postgres_data:/var/lib/postgresql/data

volumes:
  socnet_local_postgres_data:
