services:
  django:
    image: socnet_local_django
    build:
      target: python-local-run-stage
      args:
        - POETRY_GROUPS=main,local
        - GID=${GID:-1000}
        - UID=${UID:-1000}
    command:
      - bash
      - /app/docker/django/start.sh
    ports:
      - 8000:8000
    volumes:
      - .:/app
  postgres:
    volumes:
      - socnet_local_postgres_data:/var/lib/postgresql/data
  esbuild:
    image: socnet_esbuild
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      target: node
    command:
      - npm
      - run
      - watch
    networks: []
    user: node
    volumes:
      - ./socnet/static:/app/socnet/static
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
volumes:
  socnet_local_postgres_data:
