services:
  django:
    image: socnet-local-django
    build:
      target: python-local-run-stage
      args:
        - EXTRA=local
    depends_on:
      - esbuild
    ports:
      - 8000:8000
    volumes:
      - ./config:/app/config
      - ./docker:/app/docker
      - ./locale:/app/locale
      - ./socnet:/app/socnet
      - ./tests:/app/tests
      - ./manage.py:/app/manage.py
  postgres:
    volumes:
      - local-postgres-data:/var/lib/postgresql/data
  esbuild:
    image: socnet-local-esbuild
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      target: node-watch-stage
    networks:
      - esbuild
    volumes:
      - ./socnet/static/private/css:/app/socnet/static/private/css
      - ./socnet/static/private/js:/app/socnet/static/private/js
      - ./socnet/static/public/css:/app/socnet/static/public/css
      - ./socnet/static/public/js:/app/socnet/static/public/js
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
networks:
  esbuild:
volumes:
  local-postgres-data:
