services:
  django:
    image: socnet-local-django
    build:
      target: python-local-run-stage
      args:
        - POETRY_GROUPS=main,local
        - GID=${GID:-1000}
        - UID=${UID:-1000}
    depends_on:
      - esbuild
    ports:
      - 8000:8000
    volumes:
      - .:/app
  postgres:
    volumes:
      - local-postgres-data:/var/lib/postgresql/data
  esbuild:
    image: socnet-local-esbuild
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      target: node-watch-stage
      args:
        - GID=${GID:-1000}
        - UID=${UID:-1000}
    networks:
      - esbuild
    volumes:
      - ./socnet/static:/app/socnet/static
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
networks:
  esbuild:
volumes:
  local-postgres-data:
