services:
  django:
    image: socnet_local_django
    build:
      args:
        - BUILD_ENVIRONMENT=local
    command: python3 -Wd manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  postgres:
    volumes:
      - socnet_local_postgres_data:/var/lib/postgresql/data

volumes:
  socnet_local_postgres_data:
