services:
  django:
    image: socnet-production-django
    build:
      target: python-production-run-stage
      args:
        - POETRY_GROUPS=production
    depends_on:
      - redis
    networks:
      - caddy-django
      - django-redis
    restart: unless-stopped
    volumes:
      - production-django-media:/var/www/django/media
      - production-django-static:/var/www/django/static
  postgres:
    restart: unless-stopped
    volumes:
      - production-postgres-data:/var/lib/postgresql/data
  redis:
    # TODO: switch to valkey when there is a release
    image: docker.io/redis:7.2.4
    networks:
      - django-redis
    restart: unless-stopped
  caddy:
    image: socnet-production-caddy
    build:
      context: .
      dockerfile: ./docker/caddy/Dockerfile
    depends_on:
      - django
    env_file: ./.env
    networks:
      - caddy-django
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - production-caddy-config:/config
      - production-caddy-data:/data
      - production-django-media:/var/www/django/media
      - production-django-static:/var/www/django/static
networks:
  caddy-django:
  django-redis:
volumes:
  production-caddy-config:
  production-caddy-data:
  production-django-media:
  production-django-static:
  production-postgres-data:
