# This docker-compose file is required to bind ports in development,
# since binding ports in regular compose file will ruin scaling
# in production. Due to how `ports` directive is merged with two files.
version: "3.8"
services:
  web:
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    build:
      args:
        USER_ID: ${UID:-1000}
        USER_GID: ${GID:-1000}
