line-length = 80
preview = true
target-version = "py312"

[format]
docstring-code-format = true
line-ending = "lf"
skip-magic-trailing-comma = true

[lint]
ignore = [
  "A005",
  "ANN401",
  "ASYNC109",
  "BLE001",
  "C901",
  "COM812",
  "CPY001",
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D105",
  "D106",
  "D107",
  "D403",
  "D415",
  "D417",
  "DJ008",
  "DOC201",
  "DOC402",
  "DOC501",
  "FURB180",
  "ISC001",
  "PLR0904",
  "PLR0911",
  "PLR0912",
  "PLR0913",
  "PLR0914",
  "PLR0915",
  "PLR0916",
  "PLR0917",
  "PLR1702",
  "RUF001",
  "RUF002",
  "RUF003",
  "S110",
  "S112",
  "S308",
  "S311",
  "S404",
  "SIM105",
  "TD002",
  "TD003",
  "TRY400",
]
select = ["ALL"]
unfixable = ["RUF027", "T"]

[lint.per-file-ignores]
"config/settings/*" = ["F403", "F405"]
"socnet/*/migrations/*" = ["RUF012", "RUF039", "SLF001"]
"tests/*" = ["FBT001", "PLR2004", "S101"]

[lint.flake8-gettext]
extend-function-names = [
  "pgettext",
  "gettext_lazy",
  "pgettext_lazy",
  "npgettext",
  "ngettext_lazy",
  "npgettext_lazy",
]

[lint.flake8-self]
ignore-names = ["_meta", "_name_", "_value_"]

[lint.flake8-tidy-imports]
ban-relative-imports = "all"

[lint.flake8-type-checking]
exempt-modules = []
strict = true

[lint.isort]
combine-as-imports = true
required-imports = ["from __future__ import annotations"]
split-on-trailing-comma = false

[lint.pydocstyle]
convention = "google"
