# Generated by Django 4.0.5 on 2022-07-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='text',
            field=models.TextField(blank=True, max_length=4096, verbose_name='text'),
        ),
    ]
