# Generated by Django 4.0.6 on 2022-07-23 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_about_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='No more than 30 characters. Only English letters, numbers and _. Must begin with a letter and end with a letter or number.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^(?:[a-zA-Z]|[a-zA-Z][a-zA-Z\\d_]*[a-zA-Z\\d])$')], verbose_name='username'),
        ),
    ]
