# Generated by Django 4.1.7 on 2023-02-23 19:16
from __future__ import annotations

import re

import django.contrib.postgres.fields.citext
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("users", "0004_alter_user_username")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=django.contrib.postgres.fields.citext.CICharField(
                db_index=True,
                error_messages={
                    "unique": "A user with that username already exists."
                },
                help_text=(
                    "Only English letters, numbers, underscores and hyphens."
                ),
                max_length=32,
                unique=False,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers,"
                        " underscores or hyphens.",
                        "invalid",
                    )
                ],
                verbose_name="username",
            ),
        )
    ]
