# Generated by Django 4.1 on 2022-09-05 06:51

from __future__ import annotations

import django.core.validators
from django.db import migrations

import socnet.common.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_first_name_alter_user_last_name_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="about",
            field=socnet.common.fields.NormalizedTextField(
                blank=True, max_length=4096, verbose_name="about me"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=socnet.common.fields.NormalizedCharField(
                blank=True, max_length=128, verbose_name="location"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=socnet.common.fields.LowercaseCharField(
                db_index=True,
                error_messages={
                    "unique": "A user with that username already exists."
                },
                help_text=(
                    "No more than 30 characters. Only English letters, numbers"
                    " and _. Must begin with a letter and end with a letter or"
                    " number."
                ),
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?:[A-Za-z]|[A-Za-z][\\dA-Z_a-z]*[\\dA-Za-z])$"
                    )
                ],
                verbose_name="username",
            ),
        ),
    ]
