# Generated by Django 4.1.7 on 2023-02-24 06:37
from __future__ import annotations

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("users", "0005_alter_user_username")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=django.contrib.postgres.fields.citext.CIEmailField(
                max_length=254, unique=False, verbose_name="email address"
            ),
        )
    ]
