# Generated by Django 4.2 on 2023-04-03 16:49
from __future__ import annotations

import re

import django.contrib.postgres.operations
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("users", "0007_case_insensitive_collation"),
        ("users", "0008_alter_user_email_alter_user_username"),
        ("users", "0009_drop_extension_citext"),
    ]

    dependencies = [("users", "0006_alter_user_email")]

    operations = [
        django.contrib.postgres.operations.CreateCollation(
            name="case_insensitive",
            provider="icu",
            locale="und-u-ks-level2",
            deterministic=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_collation="case_insensitive",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_collation="case_insensitive",
                db_index=True,
                error_messages={
                    "unique": "A user with that username already exists."
                },
                help_text=(
                    "Only English letters, numbers, underscores and hyphens."
                ),
                max_length=32,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters,"
                        " numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
                verbose_name="username",
            ),
        ),
        migrations.RunSQL(
            sql='DROP EXTENSION IF EXISTS "citext"',
            reverse_sql='CREATE EXTENSION IF NOT EXISTS "citext"',
        ),
    ]
