# Generated by Django 4.2.1 on 2023-05-22 08:34
from __future__ import annotations

from django.db import migrations, models

import socnet.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_case_insensitive_collation_squashed_0009_drop_extension_citext")
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=socnet.users.models.image_upload_to,
                verbose_name="image",
            ),
        )
    ]
