# Generated by Django 4.2.1 on 2023-05-22 14:42
from __future__ import annotations

from django.db import migrations

import socnet.core.fields
import socnet.users.models


class Migration(migrations.Migration):
    dependencies = [("users", "0010_alter_user_image")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=socnet.core.fields.WebpImageField(
                blank=True,
                upload_to=socnet.users.models.image_upload_to,
                verbose_name="image",
            ),
        )
    ]
