# Generated by Django 4.2.1 on 2023-05-28 15:32
from __future__ import annotations

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("users", "0011_alter_user_image")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="show_last_login",
            field=models.BooleanField(
                default=True, verbose_name="show last login time in profile"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(max_length=64, verbose_name="display name"),
        ),
    ]
