# Generated by Django 4.2.2 on 2023-06-07 20:52
from __future__ import annotations

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("users", "0012_user_date_joined_user_last_login_and_more")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_collation="case_insensitive",
                error_messages={
                    "unique": "A user with that username already exists."
                },
                help_text=(
                    "Only English letters, numbers, underscores and hyphens."
                ),
                max_length=32,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters,"
                        " numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
                verbose_name="username",
            ),
        )
    ]
