# Generated by Django 4.2.2 on 2023-06-09 20:41
from __future__ import annotations

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("users", "0013_alter_user_username")]

    operations = [TrigramExtension()]
