# Generated by Django 4.1.1 on 2022-09-20 18:22
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
            options={"verbose_name": "chat", "verbose_name_plural": "chats"},
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=4096, verbose_name="text")),
                (
                    "date",
                    models.DateTimeField(auto_now_add=True, verbose_name="date/time"),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="messenger.chat",
                        verbose_name="chat",
                    ),
                ),
            ],
            options={"verbose_name": "message", "verbose_name_plural": "messages"},
        ),
    ]
