# Generated by Django 4.0.5 on 2022-07-01 13:26

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("messenger", "0002_initial")]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(max_length=4096, verbose_name="text"),
        )
    ]
