# Generated by Django 4.1.7 on 2023-03-05 12:55
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("messenger", "0002_initial")]

    operations = [
        migrations.RenameField(
            model_name="message", old_name="date", new_name="date_created"
        )
    ]
