# Generated by Django 4.1.7 on 2023-03-05 12:55
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("messenger", "0003_rename_date_message_date_created")]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date created"),
        )
    ]
