# Generated by Django 4.1 on 2022-09-05 06:51

from __future__ import annotations

from django.db import migrations

import socnet.common.fields


class Migration(migrations.Migration):
    dependencies = [("messenger", "0003_alter_message_text")]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="text",
            field=socnet.common.fields.NormalizedTextField(
                max_length=4096, verbose_name="text"
            ),
        )
    ]
