# Generated by Django 4.1.7 on 2023-03-05 14:57
from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("messenger", "0005_rename_user_message_sender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="sender",
            ),
        )
    ]
