# Generated by Django 4.1.7 on 2023-03-05 15:04
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("messenger", "0006_alter_message_sender")]

    operations = [
        migrations.RenameField(
            model_name="message", old_name="text", new_name="content"
        )
    ]
