# Generated by Django 4.1.7 on 2023-03-05 15:05
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("messenger", "0007_rename_text_message_content")]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(max_length=4096, verbose_name="content"),
        )
    ]
