# Generated by Django 4.1.7 on 2023-03-05 15:09
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("messenger", "0008_alter_message_content")]

    operations = [
        migrations.RenameField(
            model_name="chat", old_name="participants", new_name="members"
        )
    ]
