# Generated by Django 4.1.7 on 2023-03-05 15:10
from __future__ import annotations

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("messenger", "0009_rename_participants_chat_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="members",
            field=models.ManyToManyField(
                related_name="chats",
                to=settings.AUTH_USER_MODEL,
                verbose_name="members",
            ),
        )
    ]
