# Generated by Django 4.2.2 on 2023-06-07 20:52
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("messenger", "0013_alter_message_content")]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["-id"], name="messenger_m_id_b96158_idx"
            ),
        )
    ]
