# Generated by Django 4.2.7 on 2023-11-14 20:55
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("messenger", "0014_message_messenger_m_id_b96158_idx")]

    operations = [
        migrations.RemoveIndex(
            model_name="message", name="messenger_m_id_b96158_idx"
        )
    ]
