# Generated by Django 4.0.5 on 2022-06-06 17:35

from __future__ import annotations

from django.db import migrations, models

import socnet.main.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, max_length=4096, verbose_name="text"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=socnet.main.models.post_image,
                        verbose_name="image",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date/time"
                    ),
                ),
            ],
            options={
                "verbose_name": "post",
                "verbose_name_plural": "posts",
                "ordering": ("-pk",),
            },
        ),
        migrations.CreateModel(
            name="PostComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, max_length=1024, verbose_name="text"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=socnet.main.models.post_comment_image,
                        verbose_name="image",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date/time"
                    ),
                ),
            ],
            options={
                "verbose_name": "post comment",
                "verbose_name_plural": "post comments",
            },
        ),
    ]
