# Generated by Django 4.1 on 2022-09-05 06:51

from __future__ import annotations

from django.db import migrations

import socnet.core.fields


class Migration(migrations.Migration):
    dependencies = [("main", "0003_alter_postcomment_text")]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=socnet.core.fields.NormalizedTextField(
                blank=True, max_length=4096, verbose_name="text"
            ),
        ),
        migrations.AlterField(
            model_name="postcomment",
            name="text",
            field=socnet.core.fields.NormalizedTextField(
                blank=True, max_length=4096, verbose_name="text"
            ),
        ),
    ]
