# Generated by Django 4.1.1 on 2022-09-17 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("main", "0004_alter_post_text_alter_postcomment_text")]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "post", "verbose_name_plural": "posts"},
        )
    ]
