name: CI
env:
  DOCKER_BUILDKIT: 1
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cp .env.example .env
      - run: docker compose -f docker-compose.yml -f docker-compose.ci.yml build --no-cache --pull
      - run: docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm django python3 manage.py migrate
      - run: docker compose -f docker-compose.yml -f docker-compose.ci.yml run django pytest --cov --cov-report=xml
      - run: docker compose -f docker-compose.yml -f docker-compose.ci.yml down
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
