name: CI

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker compose build
      - run: docker compose run --rm django python3 manage.py migrate
      - run: docker compose run --rm django python3 -m pytest --cov-report=xml
      - run: docker compose down
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
