name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  run-pytest-mypy:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: actions/checkout@v3
      - run: cp .env.example .env
      - run: docker compose -f docker-compose.yml -f docker-compose.ci.yml pull --ignore-buildable
      - id: build
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml build --pull
      - run: docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm django python3 manage.py migrate
      - run: docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm django coverage run -m pytest
      - run: docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm django coverage report
      - if: ${{ steps.build.conclusion == 'success' }}
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm django mypy .
      - if: ${{ steps.build.conclusion == 'success' }}
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml down --remove-orphans
  run-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx run pre-commit run --all-files
  run-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
      - run: npm ci
      - run: npx eslint .
  run-tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
      - run: npm ci
      - run: npx tsc --noEmit
